# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.11.5
branches:
  only:
    - master
jdk:
  - openjdk5
  - openjdk6
  - oraclejdk5
  - oraclejdk6
#before_script:
#   - sudo apt-get install par2
